### ISSUE TITLE
Return value of pocketmine\Collectable::isGarbage() must be of the type boolean, string returned

### ISSUE THREAD

**Issue by xxFlare** [pmmp/PocketMine-MP#1224]
### Issue description

https://pastebin.com/fz22xPS2

This occurred when I attempted to join a server.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/1a7f567a70c58b0848def59118aad16557750ff3
* PHP: 7
* Server OS: Mac

### Plugins
- No running plugins when this occurred.

**Comment by dktapps** [comment]
Mind modifying the source and var_dump `isGarbage` before it's returned? I'd be interested to see what did that... that should be impossible. There's nothing in ChunkRequestTask that overwrites that field.

**Comment by xxFlare** [comment]
I'll try to reproduce again. I don't think this is related, but I just turned on the server and got this error as well:
```
php(14375,0x700006606000) malloc: *** error for object 0x7fdd9bc27a80: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by xxFlare** [comment]
More information:
```
Fatal error: Uncaught TypeError: fwrite() expects parameter 2 to be string, null given in /Users/xFlare/Desktop/PM/src/pocketmine/utils/MainLogger.php:235
Stack trace:
#0 /Users/xFlare/Desktop/PM/src/pocketmine/utils/MainLogger.php(235): fwrite(Resource id #2, NULL)
#1 [internal function]: pocketmine\utils\MainLogger->pocketmine\utils\{closure}()
#2 /Users/xFlare/Desktop/PM/src/pocketmine/utils/MainLogger.php(239): Threaded->synchronized(Object(Closure))
#3 [internal function]: pocketmine\utils\MainLogger->run()
#4 {main}
  thrown in /Users/xFlare/Desktop/PM/src/pocketmine/utils/MainLogger.php on line 235
```
Strange.

**Comment by dktapps** [comment]
The malloc() issues are related to the ZTS issues with PHP 7.0. These will be resolved when we upgrade to PHP 7.2.

**Comment by xxFlare** [comment]
Closing this since I can't reproduce it again, if I get it again with the var_dump I'll re-open.
