### ISSUE TITLE
TypeError caused by Player::getNetworkSession()

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3178]
Link to crashdump: https://pastebin.com/A8zdPzNj

Log:
```
2019-11-03 [20:05:03.271] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\player\Player::getNetworkSession() must be an instance of pocketmine\network\mcpe\NetworkSession, null returned" (EXCEPTION) in "src/player/Player" at line 666
2019-11-03 [20:05:03.273] [Server thread/DEBUG]: #0 src/entity/Entity(1670): pocketmine\player\Player->getNetworkSession()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #1 src/entity/Entity(1484): pocketmine\entity\Entity->despawnFrom(object VC\CustomPlayer)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #2 src/entity/Entity(1450): pocketmine\entity\Entity->checkChunks()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #3 src/entity/Entity(1462): pocketmine\entity\Entity->setPosition(object pocketmine\world\Position)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #4 src/entity/Entity(1568): pocketmine\entity\Entity->setPositionAndRotation(object pocketmine\world\Position, double 68.728729248047, double 27.809204101562)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #5 src/player/Player(2368): pocketmine\entity\Entity->teleport(object pocketmine\world\Position, NULL , NULL )
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #6 plugins/VC.phar/src/VC/regions/RegionGuard(461): pocketmine\player\Player->teleport(object pocketmine\world\Position)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #7 plugins/VC.phar/src/VC/regions/SelectRegion(22): VC\regions\RegionGuard->VC\regions\{closure}(object VC\CustomPlayer, string[10] podokonnik)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #8 plugins/EasyForms.phar/src/Frago9876543210/EasyForms/forms/CustomForm(71): VC\regions\SelectRegion->VC\regions\{closure}(object VC\CustomPlayer, object Frago9876543210\EasyForms\forms\CustomFormResponse)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #9 src/player/Player(2025): Frago9876543210\EasyForms\forms\CustomForm->handleResponse(object VC\CustomPlayer, array[1])
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #10 src/network/mcpe/handler/InGamePacketHandler(664): pocketmine\player\Player->onFormSubmit(integer 17, array[1])
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #11 src/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #12 src/network/mcpe/NetworkSession(349): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #13 src/network/mcpe/NetworkSession(315): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #14 src/network/mcpe/raklib/RakLibInterface(152): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[16] x.cO.d.6.....=.t)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #15 vendor/pocketmine/raklib/src/server/ServerHandler(102): pocketmine\network\mcpe\raklib\RakLibInterface->handleEncapsulated(integer 35, object raklib\protocol\EncapsulatedPacket, integer 0)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #16 src/network/mcpe/raklib/RakLibInterface(96): raklib\server\ServerHandler->handlePacket()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #17 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #18 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #19 src/Server(1765): pocketmine\snooze\SleeperHandler->sleepUntil(double 1572811503.2639)
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #20 src/Server(1308): pocketmine\Server->tickProcessor()
2019-11-03 [20:05:03.274] [Server thread/DEBUG]: #21 src/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[31] /home/server/production/server/, string[39] /home/server/production/server/plugins/)
2019-11-03 [20:05:03.275] [Server thread/DEBUG]: #22 src/PocketMine(288): pocketmine\server()
2019-11-03 [20:05:03.275] [Server thread/DEBUG]: #23 (1): require(string[75] phar:///home/server/production/server/PocketMine-MP.phar/src/PocketMine.php)
2019-11-03 [20:05:03.275] [Server thread/EMERGENCY]: Произошла фатальная ошибка и сервер вышел из строя. Создание аварийного дампа
2019-11-03 [20:05:03.279] [Server thread/EMERGENCY]: Пожалуйста, загрузите файл "/home/server/production/server/crashdumps/Sun_Nov_3-20.05.03-UTC_2019.log" в архив дампов и отправьте ссылку на страницу исправления ошибок. Дайте как можно больше информации.
2019-11-03 [20:05:03.279] [Server thread/INFO]: Выключение ServerFaultReporter v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение FloatingText v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение TempBan v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение EasyForms v1.5.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение UnixSocket v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение ChatManager v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: Выключение VC v1.0.0
2019-11-03 [20:05:03.280] [Server thread/INFO]: SophiyaFine7777 вышел из игры
2019-11-03 [20:05:03.284] [Server thread/INFO]: [NetworkSession: SophiyaFine7777] Session closed due to Server closed
2019-11-03 [20:05:03.285] [Server thread/INFO]: GaydLok вышел из игры
2019-11-03 [20:05:03.288] [Server thread/INFO]: [NetworkSession: GaydLok] Session closed due to Server closed
2019-11-03 [20:05:03.288] [Server thread/INFO]: FinestAbyss7842 вышел из игры
2019-11-03 [20:05:03.290] [Server thread/INFO]: [NetworkSession: FinestAbyss7842] Session closed due to Server closed
2019-11-03 [20:05:03.290] [Server thread/INFO]: chumdoc вышел из игры
2019-11-03 [20:05:03.291] [Server thread/INFO]: [NetworkSession: chumdoc] Session closed due to Server closed
2019-11-03 [20:05:03.292] [Server thread/INFO]: lanachai вышел из игры
2019-11-03 [20:05:03.293] [Server thread/INFO]: [NetworkSession: lanachai] Session closed due to Server closed
2019-11-03 [20:05:03.294] [Server thread/INFO]: BOGDAN 34rtp вышел из игры
2019-11-03 [20:05:03.295] [Server thread/INFO]: [NetworkSession: BOGDAN 34rtp] Session closed due to Server closed
2019-11-03 [20:05:03.295] [Server thread/INFO]: AlekSa35749 вышел из игры
2019-11-03 [20:05:03.297] [Server thread/INFO]: [NetworkSession: AlekSa35749] Session closed due to Server closed
2019-11-03 [20:05:03.297] [Server thread/INFO]: MilkeyWorld вышел из игры
2019-11-03 [20:05:03.300] [Server thread/INFO]: [NetworkSession: MilkeyWorld] Session closed due to Server closed
2019-11-03 [20:05:03.300] [Server thread/INFO]: Luza myr вышел из игры
2019-11-03 [20:05:03.302] [Server thread/INFO]: [NetworkSession: Luza myr] Session closed due to Server closed
2019-11-03 [20:05:03.302] [Server thread/INFO]: InfernalFaun284 вышел из игры
2019-11-03 [20:05:03.305] [Server thread/INFO]: [NetworkSession: InfernalFaun284] Session closed due to Server closed
2019-11-03 [20:05:03.305] [Server thread/INFO]: Nuluki1 вышел из игры
2019-11-03 [20:05:03.306] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\player\Player::getNetworkSession() must be an instance of pocketmine\network\mcpe\NetworkSession, null returned" (EXCEPTION) in "src/player/Player" at line 666
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #0 src/entity/Entity(1670): pocketmine\player\Player->getNetworkSession()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #1 src/entity/Entity(1682): pocketmine\entity\Entity->despawnFrom(object VC\CustomPlayer)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #2 src/player/Player(2120): pocketmine\entity\Entity->despawnFromAll()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #3 src/network/mcpe/NetworkSession(470): pocketmine\player\Player->disconnect(string[13] Server closed, NULL , boolean 1)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #4 src/network/mcpe/NetworkSession(450): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #5 src/network/mcpe/NetworkSession(473): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure, string[13] Server closed)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #6 src/network/NetworkSessionManager(124): pocketmine\network\mcpe\NetworkSession->disconnect(string[13] Server closed)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #7 src/Server(1581): pocketmine\network\NetworkSessionManager->close(string[13] Server closed)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #8 src/Server(1737): pocketmine\Server->forceShutdown()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #9 src/Server(1665): pocketmine\Server->crashDump()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #10 src/Server(1311): pocketmine\Server->exceptionHandler(object TypeError)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #11 src/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[31] /home/server/production/server/, string[39] /home/server/production/server/plugins/)
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #12 src/PocketMine(288): pocketmine\server()
2019-11-03 [20:05:03.306] [Server thread/DEBUG]: #13 (1): require(string[75] phar:///home/server/production/server/PocketMine-MP.phar/src/PocketMine.php)
2019-11-03 [20:05:03.307] [Server thread/EMERGENCY]: Crashed while crashing, killing process
```

Another log, note that the server did not crash and the error came from the destructor:
```
[19:22:41.364] [Server thread/INFO]: Выгрузка мира "world"
[19:22:41.447] [Server thread/INFO]: Stopping other threads


Fatal error: Uncaught TypeError: Return value of pocketmine\player\Player::getNetworkSession() must be an instance of pocketmine\network\mcpe\NetworkSession, null returned in phar:///home/server/production/server/PocketMine-MP.phar/src/player/Player.php:666
Stack trace:
#0 phar:///home/server/production/server/PocketMine-MP.phar/src/entity/Entity.php(1670): pocketmine\player\Player->getNetworkSession()
#1 phar:///home/server/production/server/PocketMine-MP.phar/src/entity/Entity.php(1682): pocketmine\entity\Entity->despawnFrom(Object(VC\CustomPlayer))
#2 phar:///home/server/production/server/PocketMine-MP.phar/src/entity/Entity.php(1726): pocketmine\entity\Entity->despawnFromAll()
#3 phar:///home/server/production/server/PocketMine-MP.phar/src/entity/Living.php(765): pocketmine\entity\Entity->onDispose()
#4 phar:///home/server/production/server/PocketMine-MP.phar/src/entity/Human.php(438): pocketmine\entity\Living->onDispose()
#5 phar:///home/server/production/server/PocketMine-MP.phar/src/player/Player.php(2152): pocketm in phar:///home/server/production/server/PocketMine-MP.phar/src/player/Player.php on line 666
```

**Comment by dktapps** [comment]
I can see a custom player class in the stack trace. Without other evidence, I can only assume that this is a fault in the way your custom Player class handles disconnecting.

**Comment by Frago9876543210** [comment]
CustomPlayer class: https://pastebin.com/TMe3FstM

**Comment by dktapps** [comment]
I need to know how to reproduce this on a clean server.

**Comment by EnderVlad96** [comment]
omgggg, gkod yarovogo

**Comment by Frago9876543210** [comment]
similar error that came from another place
```
Backtrace:
#0 src/inventory/PlayerInventory(101): pocketmine\player\Player->getNetworkSession()
#1 src/player/Player(1516): pocketmine\inventory\PlayerInventory->setHeldItemIndex(integer 1, boolean )
#2 src/network/mcpe/handler/InGamePacketHandler(361): pocketmine\player\Player->selectHotbarSlot(integer 1)
#3 src/network/mcpe/protocol/MobEquipmentPacket(73): pocketmine\network\mcpe\handler\InGamePacketHandler->handleMobEquipment(object pocketmine\network\mcpe\protocol\MobEquipmentPacket)
#4 src/network/mcpe/NetworkSession(349): pocketmine\network\mcpe\protocol\MobEquipmentPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler)
#5 src/network/mcpe/NetworkSession(315): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\MobEquipmentPacket)
#6 src/network/mcpe/raklib/RakLibInterface(152): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[25] x..Wda@.......(...... ...)
#7 vendor/pocketmine/raklib/src/server/ServerHandler(102): pocketmine\network\mcpe\raklib\RakLibInterface->handleEncapsulated(integer 149, object raklib\protocol\EncapsulatedPacket, integer 0)
#8 src/network/mcpe/raklib/RakLibInterface(96): raklib\server\ServerHandler->handlePacket()
#9 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#10 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
#11 src/Server(1765): pocketmine\snooze\SleeperHandler->sleepUntil(double 1573294823.9097)
#12 src/Server(1308): pocketmine\Server->tickProcessor()
#13 src/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[31] /home/server/production/server/, string[39] /home/server/production/server/plugins/)
#14 src/PocketMine(288): pocketmine\server()
#15 (1): require(string[75] phar:///home/server/production/server/PocketMine-MP.phar/src/PocketMine.php)
```

**Comment by dktapps** [comment]
I think this commit is related: https://github.com/pmmp/PocketMine-MP/commit/3028832cd35c53937bb6502f74d3ad53646b12a7

This will cause problems with untracked players being referenced by entities when using `spawnTo()` if the target player isn't using the target chunk. This bug can also be triggered by `showPlayer()`.

**Comment by dktapps** [comment]
any news on this?

**Comment by dktapps** [comment]
Closing due to lack of response.
