### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by Renual1337** [pmmp/PocketMine-MP#896]
Hi guys,

We're seeing random segmentation faults occur, here's a backtrace:

(This happens during normal gameplay, nothing specific, sometimes happens on boot)

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x0000000000a19adb in zend_mm_alloc_small (heap=0x7f9e5fe00040, size=56, bin_num=6,
__zend_filename=0xe457c0 "/pocketmine/install_data/php/Zend/zend_vm_execute.h", __zend_lineno=28903,
__zend_orig_filename=0x0, __zend_orig_lineno=0) at /pocketmine/install_data/php/Zend/zend_alloc.c:1295
1295	/pocketmine/install_data/php/Zend/zend_alloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9e620f17c0 (LWP 17132))]
(gdb) backtrace
#0 0x0000000000a19adb in zend_mm_alloc_small (heap=0x7f9e5fe00040, size=56, bin_num=6,
__zend_filename=0xe457c0 "/pocketmine/install_data/php/Zend/zend_vm_execute.h", __zend_lineno=28903,
__zend_orig_filename=0x0, __zend_orig_lineno=0) at /pocketmine/install_data/php/Zend/zend_alloc.c:1295
#1 0x0000000000a19db9 in zend_mm_alloc_heap (heap=0x7f9e5fe00040, size=56,
__zend_filename=0xe457c0 "/pocketmine/install_data/php/Zend/zend_vm_execute.h", __zend_lineno=28903,
__zend_orig_filename=0x0, __zend_orig_lineno=0) at /pocketmine/install_data/php/Zend/zend_alloc.c:1366
#2 0x0000000000a1cccc in _emalloc (size=24, __zend_filename=0xe457c0 "/pocketmine/install_data/php/Zend/zend_vm_execute.h",
__zend_lineno=28903, __zend_orig_filename=0x0, __zend_orig_lineno=0)
at /pocketmine/install_data/php/Zend/zend_alloc.c:2450
#3 0x0000000000b0d6d2 in ZEND_SEND_REF_SPEC_CV_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:28903
#4 0x0000000000b0d7f9 in ZEND_SEND_VAR_EX_SPEC_CV_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:28924
#5 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe18170) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#6 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe18170)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#7 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#8 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe18020) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#9 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe18020)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#10 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#11 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe17960) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#12 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe17960)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#13 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#14 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe17830) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#15 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe17830)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#16 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#17 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe17260) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#18 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe17260)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#19 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#20 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe15190) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#21 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe15190)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#22 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#23 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe140b0) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#24 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe140b0)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#25 0x0000000000ad3fb2 in ZEND_INCLUDE_OR_EVAL_SPEC_CONST_HANDLER ()
at /pocketmine/install_data/php/Zend/zend_vm_execute.h:3687
#26 0x0000000000ac9c88 in execute_ex (ex=0x7f9e5fe14030) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
---Type to continue, or q to quit---
#27 0x0000000000768ccc in pthreads_execute_ex (data=0x7f9e5fe14030)
at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#28 0x0000000000ac9e97 in zend_execute (op_array=0x7f9e5fe7f000, return_value=0x0)
at /pocketmine/install_data/php/Zend/zend_vm_execute.h:458
#29 0x0000000000a5e646 in zend_execute_scripts (type=8, retval=0x0, file_count=3)
at /pocketmine/install_data/php/Zend/zend.c:1427
#30 0x000000000099691e in php_execute_script (primary_file=0x7ffd327292f0) at /pocketmine/install_data/php/main/main.c:2494
#31 0x0000000000b3bdb0 in do_cli (argc=2, argv=0x11c62f0) at /pocketmine/install_data/php/sapi/cli/php_cli.c:974
#32 0x0000000000b3d2ec in main (argc=2, argv=0x11c62f0) at /pocketmine/install_data/php/sapi/cli/php_cli.c:1344

Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x000000000080a168 in zif_call_user_func (execute_data=0xe82130, return_value=0x688998014030)
at /pocketmine/install_data/php/ext/standard/basic_functions.c:4776
4776	/pocketmine/install_data/php/ext/standard/basic_functions.c: No such file or directory.
(gdb) backtrace
#0 0x000000000080a168 in zif_call_user_func (execute_data=0xe82130, return_value=0x688998014030)
at /pocketmine/install_data/php/ext/standard/basic_functions.c:4776
#1 0x0000000000000000 in ?? ()

Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x0000000000a99d2a in gc_mark_grey (ref=0x7f2126a2bc00)
at /pocketmine/install_data/php/Zend/zend_gc.c:479
479	/pocketmine/install_data/php/Zend/zend_gc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f212a3f97c0 (LWP 25494))]
(gdb) backtrace
#0 0x0000000000a99d2a in gc_mark_grey (ref=0x7f2126a2bc00)
at /pocketmine/install_data/php/Zend/zend_gc.c:479
#1 0x0000000000a99e89 in gc_mark_grey (ref=0x7f2126a2bc00)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#2 0x0000000000a99e89 in gc_mark_grey (ref=0x7f2126a30000)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#3 0x0000000000a99e89 in gc_mark_grey (ref=0x7f2126b16900)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#4 0x0000000000a99e89 in gc_mark_grey (ref=0x7f2124172200)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#5 0x0000000000a99b97 in gc_mark_grey (ref=0x7f21031cacc0)
at /pocketmine/install_data/php/Zend/zend_gc.c:444
#6 0x0000000000a99b97 in gc_mark_grey (ref=0x7f2103157800)
at /pocketmine/install_data/php/Zend/zend_gc.c:444
#7 0x0000000000a99b97 in gc_mark_grey (ref=0x7f21033c8280)
at /pocketmine/install_data/php/Zend/zend_gc.c:444
#8 0x0000000000a99e89 in gc_mark_grey (ref=0x7f20ea950180)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#9 0x0000000000a99e89 in gc_mark_grey (ref=0x7f20f49c8a00)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#10 0x0000000000a99e89 in gc_mark_grey (ref=0x7f20f6e25200)
at /pocketmine/install_data/php/Zend/zend_gc.c:505
#11 0x0000000000a99e89 in gc_mark_grey (ref=0x7f20f6e25900)
#12 0x0000000000a99fbc in gc_mark_roots () at /pocketmine/install_data/php/Zend/zend_gc.c:531
#13 0x0000000000a9ba7a in zend_gc_collect_cycles () at /pocketmine/install_data/php/Zend/zend_gc.c:1003
#14 0x0000000000a7b232 in zif_gc_collect_cycles (execute_data=0x7f2128018560, return_value=0x7f2128018530)
at /pocketmine/install_data/php/Zend/zend_builtin_functions.c:390
#15 0x0000000000aca4dd in ZEND_DO_ICALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:586
#16 0x0000000000ac9c88 in execute_ex (ex=0x7f21280184c0) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#17 0x0000000000768ccc in pthreads_execute_ex (data=0x7f21280184c0) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#18 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#19 0x0000000000ac9c88 in execute_ex (ex=0x7f2128018430) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#20 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128018430) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#21 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#22 0x0000000000ac9c88 in execute_ex (ex=0x7f2128018100) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#23 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128018100) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#24 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#25 0x0000000000ac9c88 in execute_ex (ex=0x7f2128017a50) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#26 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128017a50) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#27 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#28 0x0000000000ac9c88 in execute_ex (ex=0x7f2128017920) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#29 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128017920) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#30 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#31 0x0000000000ac9c88 in execute_ex (ex=0x7f2128017340) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#32 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128017340) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#33 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#34 0x0000000000ac9c88 in execute_ex (ex=0x7f21280150f0) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#35 0x0000000000768ccc in pthreads_execute_ex (data=0x7f21280150f0) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#36 0x0000000000acb20d in ZEND_DO_FCALL_SPEC_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:800
#37 0x0000000000ac9c88 in execute_ex (ex=0x7f21280140b0) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#38 0x0000000000768ccc in pthreads_execute_ex (data=0x7f21280140b0) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#39 0x0000000000ad3fb2 in ZEND_INCLUDE_OR_EVAL_SPEC_CONST_HANDLER () at /pocketmine/install_data/php/Zend/zend_vm_execute.h:3687
#40 0x0000000000ac9c88 in execute_ex (ex=0x7f2128014030) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:414
#41 0x0000000000768ccc in pthreads_execute_ex (data=0x7f2128014030) at /pocketmine/install_data/php/ext/pthreads/php_pthreads.c:143
#42 0x0000000000ac9e97 in zend_execute (op_array=0x7f212808d000, return_value=0x0) at /pocketmine/install_data/php/Zend/zend_vm_execute.h:458
#43 0x0000000000a5e646 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /pocketmine/install_data/php/Zend/zend.c:1427
#44 0x000000000099691e in php_execute_script (primary_file=0x7fff240cd870) at /pocketmine/install_data/php/main/main.c:2494
#45 0x0000000000b3bdb0 in do_cli (argc=2, argv=0x11c62f0) at /pocketmine/install_data/php/sapi/cli/php_cli.c:974
#46 0x0000000000b3d2ec in main (argc=2, argv=0x11c62f0) at /pocketmine/install_data/php/sapi/cli/php_cli.c:1344

Program terminated with signal SIGSEGV, Segmentation fault.
0x00000000007e1fcc in BF_crypt (key=0x100000000 <error: Cannot access memory at address 0x100000000>,
setting=0x7ffd00000000 <error: Cannot access memory at address 0x7ffd00000000>, output=0x7ffd9d895d80 " \023\273W\305\177", size=32709, min=1470199296)
at /pocketmine/install_data/php/ext/standard/crypt_blowfish.c:740
740	/pocketmine/install_data/php/ext/standard/crypt_blowfish.c: No such file or directory.
(gdb) backtrace
#0 0x00000000007e1fcc in BF_crypt (key=0x100000000 <error: Cannot access memory at address 0x100000000>,
setting=0x7ffd00000000 <error: Cannot access memory at address 0x7ffd00000000>, output=0x7ffd9d895d80 " \023\273W\305\177", size=32709, min=1470199296)
at /pocketmine/install_data/php/ext/standard/crypt_blowfish.c:740
#1 0x00000000000041ed in ?? ()
#2 0x0000000000000000 in ?? ()

**Comment by dktapps** [comment]
This is a PHP issue, not PocketMine. #90
